name: PDF & README

on:
  push:
    paths:
      - 'relazione.ltx'
      - 'assets_relazione/readme.lua'
      - '.github/workflows/update_docs.yml'

permissions:
  contents: write

jobs:
  build_and_update:
    runs-on: ubuntu-22.04 
    
    steps:
      - name: Checkout del codice
        uses: actions/checkout@v4

      - name: Setup Pandoc
        uses: pandoc/actions/setup@v1

      - name: Genera README.md da LaTeX
        run: |
          pandoc relazione.ltx -f latex -t gfm --lua-filter=assets_relazione/readme.lua --wrap=none -o README.md

      - name: Setup Tectonic
        uses: wtfjoke/setup-tectonic@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Tectonic packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/Tectonic
          key: ${{ runner.os }}-tectonic-${{ hashFiles('relazione.ltx') }}
          restore-keys: |
            ${{ runner.os }}-tectonic-

      - name: Compila PDF con Tectonic
        run: tectonic relazione.ltx

      - name: Commit e Push dei cambiamenti
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: aggiornamento relazione"
          file_pattern: 'README.md relazione.pdf'